Sprint 3
vitkovsky21/middle.messenger.praktikum.yandex pull request #18
Opened 2022-08-16 15:32 UTC by vitkovsky21

2022-08-16 20:39 UTC, podlovchenko requested changes
Привет) Не получается проверить работу приложения, при входе или регистрации ответ `Cookie is not valid`, cookies чистила
При перезагрузке страницы `Cannot GET /error`

2022-08-16 20:39 UTC, podlovchenko commented on .mocharc.json
> +}
Ошибка EOF

2022-08-16 20:39 UTC, podlovchenko commented on babel.config.js
> +  return { presets };
Этот файл не нужен

2022-08-16 20:39 UTC, podlovchenko commented on package.json
> +    "@babel/cli": "^7.18.10",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-08-16 20:39 UTC, podlovchenko commented on src/api/auth.ts
> +  signUp: (data: SignUpRequestData): Promise<unknown> => new HTTPTransport().post(`${host}api/v2/auth/signup`, { data, headers: { 'Content-Type': 'application/json' } }),
Было бы здорово задать типы для возвращаемых значений

2022-08-16 20:39 UTC, podlovchenko commented on src/api/auth.ts
> +  login: (data: LoginRequestData): Promise<unknown> => new HTTPTransport().post(`${host}api/v2/auth/signin`, { data, headers: { 'Content-Type': 'application/json' } }),
Добавление заголовка { 'Content-Type': 'application/json' } можно внести внутрь HTTPTransport в зависимости от типа data

2022-08-16 20:39 UTC, podlovchenko commented on src/api/auth.ts
> +  me: (): Promise<unknown> => new HTTPTransport().get(`${host}api/v2/auth/user`),
Зачем каждый раз создается новый объект HTTPTransport? Лучше создать объект и использовать его или сделать HTTPTransport синглтоном

2022-08-16 20:39 UTC, podlovchenko commented on src/api/changeData.ts
> +const host = 'https://ya-praktikum.tech/';
Этот host для всех api, лучше вынести в файл с константами

2022-08-16 20:39 UTC, podlovchenko commented on src/api/chats.ts
> +  chatId: number;
Используется наименование полей то в snake_case, то в camelCase
Лучше выбрать что-то одно

2022-08-16 20:39 UTC, podlovchenko commented on src/api/chats.ts
> +  users: any[]
Стоит добавить тип для юзеров

2022-08-16 20:39 UTC, podlovchenko commented on src/api/chats.ts
> +type userRequest = {
Типы обычно именуются как в первом варианте в PascalCase

2022-08-16 20:39 UTC, podlovchenko commented on src/components/chat/chat.ts
> +  chat: any;
Почему все через any?

2022-08-16 20:39 UTC, podlovchenko commented on src/core/Block.ts
>  export default class Block<P = any> {
```suggestion
export default class Block<P extends {}> {
```

2022-08-16 20:39 UTC, podlovchenko commented on src/core/Block.ts
> +  _componentWillUnmount() {
Для приватных методов не хватает модификатора private

2022-08-16 20:39 UTC, podlovchenko commented on src/core/chatApi.ts
> +// }
Закомментированный код лучше не оставлять в проекте

2022-08-16 20:39 UTC, podlovchenko commented on src/core/requestApi.ts
> +const enum METHOD {
enum обычно именуется в формате PascalCase

2022-08-16 20:39 UTC, podlovchenko commented on src/core/requestApi.ts
> +    headers?: { [key: string]: string };
```suggestion
    headers?: Record<string, string>;
```

2022-08-16 20:39 UTC, podlovchenko commented on src/core/requestApi.ts
>              xhr.open(method, url);
Для method нужно указать значение по умолчанию, так как указан необязательным свойством

2022-08-16 20:39 UTC, podlovchenko commented on src/styles/main/main.scss
> +        border: 1px solid #e9e9e9;
Цвета лучше указывать через css переменные, так будет понятнее, что это за цвет при просмотре кода и проще редактировать цвета по всему проекту

2022-08-16 21:46 UTC, vitkovsky21 commented on .mocharc.json
> +}
https://cosmic-valkyrie-60368c.netlify.app/ - забыл нажать publish deploy, здесь тоже не получается войти и зарегистрироваться?

Просто я попробовал у себя, тоже почистил cookies, всё собирается, регистрация проходит.

2022-08-17 14:40 UTC, vitkovsky21 commented on babel.config.js
> +  return { presets };
Без него тесты не запускаются.

2022-08-17 14:41 UTC, vitkovsky21 commented on .mocharc.json
> +}
Ошибки EOF тоже нет, странно

2022-08-17 14:42 UTC, vitkovsky21 commented on babel.config.js
> +  return { presets };
Хотя во время сборки в консоли ругается на этот файл.

2022-08-17 14:51 UTC, vitkovsky21 commented on .mocharc.json
> +}
Сейчас ещё раз попробовал с разных устройств пересобранную версию, и всё работает.
Ну то есть по мнению netlify и разных устройств у меня дома всё вроде должно нормально функционировать.

Там правда я забыл исправить косяк, что при подключению к чату постоянно Hello отправляется ：)

2022-08-17 14:52 UTC, vitkovsky21 commented on src/core/chatApi.ts
> +// }
А этот файл вообще не знаю, что тут забыл

2022-08-17 15:00 UTC, vitkovsky21 commented on src/api/auth.ts
> +  me: (): Promise<unknown> => new HTTPTransport().get(`${host}api/v2/auth/user`),
Вроде исправил

2022-08-17 15:00 UTC, vitkovsky21 commented on src/api/changeData.ts
> +const host = 'https://ya-praktikum.tech/';
Вынес

2022-08-17 15:01 UTC, vitkovsky21 commented on src/api/chats.ts
> +  chatId: number;
Так это в swagger почему-то в одних случаях один case, в других другой: при добавлении юзера в чат camelCase, а при регистрации и в других случаях уже нет.

2022-08-17 15:01 UTC, vitkovsky21 commented on src/api/chats.ts
> +  users: any[]
Добавил

2022-08-17 15:02 UTC, vitkovsky21 commented on src/api/chats.ts
> +  users: any[]
А не, не добавил. Но добавлю)
Я там number[] планировал добавить.

2022-08-17 15:03 UTC, vitkovsky21 commented on src/components/chat/chat.ts
> +  chat: any;
А сам в шоке

2022-08-17 15:04 UTC, vitkovsky21 commented on src/core/requestApi.ts
>              xhr.open(method, url);
Вроде бы всё правильно понял и исправил

2022-08-17 15:23 UTC, podlovchenko commented on .mocharc.json
> +}
Сейчас все окей)

2022-08-17 15:31 UTC, podlovchenko requested changes
Привет)

Все еще при перезагрузке страницы `Cannot GET`
Нужно добавить в index.js
```
app.get('/'*, (req, res) => {
  res.sendFile(resolve(__dirname, 'dist', 'index.html'));
});
```
Аватар не отображается
<img width="314" alt="Снимок экрана 2022-08-17 в 18 30 34" src="https://user-images.githubusercontent.com/22602747/185180522-6aec04a7-d231-46d0-acf2-e05eefe28989.png">
Отправку Hello в чате каждый раз лучше убрать

2022-08-17 15:31 UTC, podlovchenko commented on src/api/Base.ts
> +export default abstract class BaseAPI {
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая [статья](https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/) на эту тему

2022-08-17 15:32 UTC, podlovchenko commented on .mocharc.json
> +}
<img width="724" alt="Снимок экрана 2022-08-17 в 18 32 00" src="https://user-images.githubusercontent.com/22602747/185180776-729a00a8-20fe-4384-a36e-b46ea3acdbf1.png">

2022-08-17 15:49 UTC, vitkovsky21 commented on src/api/Base.ts
> +export default abstract class BaseAPI {
Окей, спасибо, ознакомлюсь.

2022-08-17 16:12 UTC, vitkovsky21 commented
А, только заметил. Он png не ставит аватаркой, только jpg вроде.

Исправил ошибку при перезагрузке, и когда запускаю через npm run start, то "cannot GET" нет.
А вот netlify не нравится что-то.
И исправил слегка иначе, а то не получалось при помощи resolve.

2022-08-17 17:11 UTC, podlovchenko commented
На нетлифае нужно добавить redirects 
https://docs.netlify.com/routing/redirects/

Работу принимаю)

2022-08-24 08:00 UTC, merged